swagger: "2.0"
info:
  title: API NEST JS
  version: 1.0.0
  description: STUDY NODEJS (NEST-JS) API
paths:
  /login:
    post:
      tags:
        - Auth
      summary: User login
      description: Endpoint for user login.
      parameters:
        - name: body
          in: body
          required: true
          schema:
            type: object
            properties:
              tel:
                type: string
                description: User telephone number.
              password:
                type: string
                description: User password.
      responses:
        "200":
          description: Login successful
        "400":
          description: Bad request
        "401":
          description: Unauthorized
