version: '3.8'

services:
  db:
    image: postgres:15
    container_name: nestjs_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: data_nest_app
    ports:
      - '5432:5432'
volumes:
  postgres_data:
